- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3

- project:
    masakari-systemfault-integration-ci:
      jobs:
        - masakari-build-test

- job:
    name: masakari-build-test
    parent: base
